
UNITTESTS?=1

CXXFLAGS= -I. -std=c++11 -Wall -g -O99 \
  -DALPHA_UNITTESTS=$(UNITTESTS)
LDFLAGS=

AUTOGENERATED_FILES=\
  segdata.h \
  lex.BaseWeights.cc \
  lex.BaseInput.cc \
  lex.BaseIntermediate.cc \
  lex.BaseBounds.cc

TARGETS= riscv-lut-compiler

OBJ=
all: make.incl $(TARGETS)

make.incl: $(AUTOGENERATED_FILES)
	./builddep.py > make.incl

%.l: %.li
	cat $^ | ./preparse-flex.py > $@

%.cc: %.l
	flex $^

include make.incl


riscv-lut-compiler: $(OBJ)
	$(CXX) $^ -o$@ $(LDFLAGS)


segdata.h: segdata-incl.h
	./mksegdata.py

tests: all $(TESTS)

clean:
	rm -f $(OBJ) $(TARGETS) $(AUTOGENERATED_FILES) make.incl

install:
	install riscv-lut-compiler $(RISCV)/bin

doc:
	doxygen lut-compiler.doxygen
