#!/usr/bin/env python3

as_code=""
as_string="#define SEG_DATA_DECL \\\n"

replacements={
  "\n":"\\n",
  "\r":"\\r",
  "\"":"\\\"",
}


with open("segdata-incl.h","r") as f:
  for ln in f:
    as_code+=ln
    as_string+=(
      "\"%s\" \\\n"
      %"".join([ replacements[v] if v in replacements else v for v in ln]))

with open("segdata.h","w") as f:
  f.write(
    "/* THIS FILE IS AUTOMATICALLY GENERATED FROM segdata-incl.h. */\n"
    "/* DO NOT MODIFY IT DIRECTLY */\n"
    "#ifndef RISCV_LUT_COMPILER_SEGDATA_H\n"
    "#define RISCV_LUT_COMPILER_SEGDATA_H\n\n")
  f.write(as_code)
  f.write(as_string)
  f.write("\n#endif\n")
